### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by GarfieldR** [raffam/eurosportplayer-dl#1]
hi ,can you do a windows version?

**Comment by raffam** [comment]
Now there is a release as a windows binary under the "Release" tab of the GitHub project page

**Comment by GarfieldR** [comment]
********** STEP 1 **********
Traceback (most recent call last):
  File "eurosportplayer-dl.py", line 783, in <module>
  File "eurosportplayer-dl.py", line 586, in main
  File "eurosportplayer-dl.py", line 310, in get_client_api_key
AttributeError: 'NoneType' object has no attribute 'group'
[6412] Failed to execute script eurosportplayer-dl
i use the windows version, that's the console print info, is anything wrong?
eurosportplayer-dl.exe --url "https://gb.eurosportplayer.com/video/eurocup-ratiopharm-ulm-v-galatasaray-istanbul/68881112" --user "*****@163.com" --password "******"

**Comment by raffam** [comment]
Looks like something is changing in the website. Can you open another issue?

**Comment by raffam** [comment]
Can you try to download the new version and run it appending the new `--partner` parameter to the command line?

**Comment by GarfieldR** [comment]
it works now, thanks
