### ISSUE TITLE
 No module named 'fake_useragent'

### ISSUE THREAD

**Issue by hagicohen** [raffam/eurosportplayer-dl#10]
Thank you for your supporting.

I get the same issue as before after insall FFMPEG, than I update to new relase and now I get this issue:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 40, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

**Comment by raffam** [comment]
Hello, you need to run "pip3 install fake_useragent" and make sure ffmpeg is in path

**Comment by raffam** [comment]
Please re-open the issue if you experience other problems
