### ISSUE TITLE
downloads the segments but doesn't combine them?

### ISSUE THREAD

**Issue by simowilso** [raffam/eurosportplayer-dl#11]
** Preliminary info **
eurosportplayer-dl version:
source
Python version (in case you are running from source code): 3.7.4 (Windows)

** Description **
This is a really nice script. I can download the video but I get 1021 separate video clips at the end, they are not combined into one single file. Seems like it could be a problem with ffmpeg. Any tips where to look what is going wrong?

**Comment by raffam** [comment]
Does the script gives you a warning at the start saying that ffmpeg was not found?
Try to open a command line (start->run->"cmd"->ok) and type "ffmpeg" and press enter. What do you get?

**Comment by simowilso** [comment]
Hi,

Thanks for the quick response. I initially got the warning that ffmpeg wasn't in the path but I still pressed continue. This is how I initially got all the segments.

Then I made sure ffmpeg was in the path, and re-ran. I also tried deleting all the video segments and running again but they just got downloaded again and not combined. Are there some other files I should try deleting before trying again?
________________________________

**Comment by raffam** [comment]
You should not / have not to delete any files.
Can you open a command line (start->run->"cmd"->ok), type "ffmpeg" and press enter, and report what you get?

**Comment by simowilso** [comment]
ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190716
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

________________________________

**Comment by raffam** [comment]
I am basically out of options. I have no explanation whatsoever for why ffmpeg should be in path on an environment created manually but not in the one created by Python.

Do you still get the message of "ffmpeg not found" at the beginning of the script?
Can you try to resume the download (`eurosportplayer-dl.py --resume --password MYPASSWORD --debug`) and post both the output in the console and the log file?

**Comment by frederic1** [comment]
Hello,

The videos are not joined for me either.

FFMPEG was installed and added manually in the "path" environnement variable. I haven't had any warning saying that FFMPEG is not present.

> J:\_EPDL>ffmpeg -version
> ffmpeg version N-94481-g5ac28e9cc1 Copyright (c) 2000-2019 the FFmpeg developers
> 
> built with gcc 9.1.1 (GCC) 20190716
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig
--enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libblu
ray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable
-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --ena
ble-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-l
ibvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --e
nable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable
-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enab
le-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enab
le-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --ena
ble-dxva2 --enable-avisynth --enable-libopenmpt
> libavutil      56. 33.100 / 56. 33.100
> libavcodec     58. 55.100 / 58. 55.100
> libavformat    58. 30.100 / 58. 30.100
> libavdevice    58.  9.100 / 58.  9.100
> libavfilter     7. 58.100 /  7. 58.100
> libswscale      5.  6.100 /  5.  6.100
> libswresample   3.  6.100 /  3.  6.100
> libpostproc    55.  6.100 / 55.  6.100`





> J:\_EPDL>eurosportplayer-dl.py --resume --password Pass1word --debug >log.txt
> (...)
> Skipping frame 3683 (continuing previous download)
> Skipping frame 3684 (continuing previous download)
> 100%|██████████████████████████████████████████████| 3685/3685 [00:00<?, ?it/s]
Video downloaded

**Comment by raffam** [comment]
I was able to reproduce the bug on Windows :)

@frederic1 @simowilso Can you try the latest commit?

**Comment by frederic1** [comment]
I'm sorry and embarrassed, I don't know what you mean by "try the latest commit". Do you want me to redownload the ZIP ?

**Comment by raffam** [comment]
Yes exactly, please download the zip file with the latest code again

**Comment by frederic1** [comment]
> J:\_EPDL>eurosportplayer-dl.py --resume --password Pass1word --debug
Traceback (most recent call last):
  File "J:\_EPDL\eurosportplayer-dl.py", line 870, in <module>
    setup_loggers(args)
  File "J:\_EPDL\eurosportplayer-dl.py", line 597, in setup_loggers
    fh = logging.FileHandler(log_fp, mode='w')
  File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1087,
in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files (x86)\Python37-32\lib\logging\__init__.py", line 1116,
in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'J:\\_EPDL\\.eurosportpl
ayer-dl\\logs\\eurosportplayer-dl.log'

**Comment by frederic1** [comment]
EDIT : I have fixed the previous quote (some characters were uncorrectly escaped)

**Comment by frederic1** [comment]
I have made a fresh install and it work PERCTLY NOW !!!! The 5-hour tennis brodcast I've just downloaded plays flawlessly. Raffam thanks for your fantastic work ! You can't imagine all the time I wasted looking for a software that is able to download Eurosport Player videos without success. I even paid for GETFLV that doesn't work. Othe rsoftware produce a DRM protected file. 

I read another topic when you asked youtubedl's creator to implement EurosportPlayer compatibility but he apparently didn't want to do it. You finally did it yourself. We are really lucky to have you here.

**Comment by simowilso** [comment]
Brilliant thank you. I was able to manually combine the segments for the one I needed but great utility and thanks for fixing so fast.

**Comment by raffam** [comment]
Hello, thanks for your support. I am glad that my work is useful also for others.

I was able to reproduce the bug on Windows and fixed it yesterday. Moreover I realized that Pyinstaller now works correctly, so I was able to produce an .exe file for Windows. You find it in the [release section](https://github.com/raffam/eurosportplayer-dl/releases/tag/v1.4)

Best
