### ISSUE TITLE
Guide on how to make this script work on Windows

### ISSUE THREAD

**Issue by frederic1** [raffam/eurosportplayer-dl#12]
Hello,

First of all thanks for this awesome script. It would be nice if you made a Step-By-Step guide explaining how to make it work with Windows' version of Python. I haven't even managed to install its dependencies. It's very frustrating because I badly need to download Eurosportlayer videos (I have a legit account), the script to do it is here, right in my eyes but I can't use it :-(

My dream would be if you could make a .exe out of it because using Python on Windows is a pain and the documentation is complicated. 

Thanks.

Cedric from Paris.

**Comment by raffam** [comment]
There was once upon a time a .exe for Windows, but unfortunately I had to switch from an old, unsupported library (called Pycrypto) to a new one (called pycryptodome), and after the change Pyinstaller was not able to generate a working .exe anymore. I will try with the new version of Pyinstaller or I will try to change the compiler for Windows.

Anyway, you basically go to www.python.org and download and install python for Windows. The you download the source code (you can also go to the github homepage of the script, and click on "Clone or download"->Download). Then you open a command line (start->run->"cmd"->Ok) and go to the folder where you extracted the source code. Then you run "python -r requirements.txt" to install the dependencies, and finally you can run the script.

I know it may sound complicated if you are unfamiliar with Python and in fact it is, but anyway I will retry to compile an executable in the next days or make a more detailed guide

**Comment by frederic1** [comment]
Hey thanks for the quick reply Raffam ! It works ! (I just had to install FFMPEG and add it to the path environnement for your script to use it). The script is currently downloading the video, I'll let you know if I can read it !

**Comment by raffam** [comment]
I realized that Pyinstaller now works correctly with pycryptodome, so I was able to produce an .exe file for Windows. 

Nevertheless the resulting file was too big (70MB) so I was able to remove dependency from tqdm and sqitched from pycryptodome to cryptography.

You can find the latest .exe file for Windows in the [release section](https://github.com/raffam/eurosportplayer-dl/releases/tag/v1.4)
