### ISSUE TITLE
Downloads random videos

### ISSUE THREAD

**Issue by fatlazycat** [raffam/eurosportplayer-dl#3]
Worked before but now appears to download some random show rather than the one expected.

Any ideas ?

**Comment by fatlazycat** [comment]
Reverted to commit cc8340da7a28641b0b457218eb8718449732c570 and working again

**Comment by raffam** [comment]
Can you post a link on which I can test your issue?

**Comment by fatlazycat** [comment]
Am travelling at the moment, will post next week.

**Comment by raffam** [comment]
It should be fixed in the latest commit. Please reopen this issue if it should not be so
