### ISSUE TITLE
no plan

### ISSUE THREAD

**Issue by thomas012345** [raffam/eurosportplayer-dl#4]
[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3099308/eurosport-dl.log)

File "eurosportplayer-dl.py", line 872, in <module>
  File "eurosportplayer-dl.py", line 825, in main
  File "eurosportplayer-dl.py", line 594, in concat_video_frames
  File "subprocess.py", line 323, in call
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
[9088] Failed to execute script eurosportplayer-dl

**Comment by raffam** [comment]
Do you have ffmpeg installed in your system and in the path?

**Comment by thomas012345** [comment]
I installed ffmpeg via "pip install" or whats the right path?

 

same dir as eurosportplayer-dl???

 

Gesendet: Samstag, 20. April 2019 um 06:05 Uhr
Von: "Raffaele Mancuso" <notifications@github.com>
An: raffam/eurosportplayer-dl <eurosportplayer-dl@noreply.github.com>
Cc: thomas012345 <sidux123@web.de>, Author <author@noreply.github.com>
Betreff: Re: [raffam/eurosportplayer-dl] no plan (#4)


Do you have ffmpeg installed in your system and in the path?

**Comment by raffam** [comment]
No, you install ffmpeg from ffmpeg.org and make sure that the executable is in the path

**Comment by thomas012345** [comment]
ok, thanks.  Working now partitial, its recording 20 min...  But the stream is about 6 hours

[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3100314/eurosport-dl.log)

********** STEP 1 **********
********** STEP 2 **********
********** STEP 3 **********
********** STEP 4 **********
********** STEP 5 **********
********** STEP 6 **********
********** STEP 7 **********
Found resolution: 896x504
Found resolution: 320x180
Found resolution: 384x216
Found resolution: 512x288
Found resolution: 640x360
Found resolution: 960x540
Found resolution: 1280x720
0. 896x504 - URL: 1800_complete.m3u8
1. 320x180 - URL: 192_complete.m3u8
2. 384x216 - URL: 450_complete.m3u8
3. 512x288 - URL: 800_complete.m3u8
4. 640x360 - URL: 1200_complete.m3u8
5. 960x540 - URL: 2500_complete.m3u8
6. 1280x720 - URL: 3500_complete.m3u8
Choose the stream you want: 1
[==================================================] 100.00% (828/828)File './download/final.mp4' already exists. Overwrite ? [y/N] y
Video downloaded
Traceback (most recent call last):
  File "eurosportplayer-dl.py", line 874, in <module>
NameError: name 'exit' is not defined
[2196] Failed to execute script eurosportplayer-dl

**Comment by raffam** [comment]
Can you try with the latest commit?

**Comment by thomas012345** [comment]
different Error-Code, but same result...

(thanks for your effort)


[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3101692/eurosport-dl.log)


********** STEP 1 **********
********** STEP 2 **********
********** STEP 3 **********
********** STEP 4 **********
********** STEP 5 **********
********** STEP 6 **********
********** STEP 7 **********
Found resolution: 896x504
Found resolution: 320x180
Found resolution: 384x216
Found resolution: 512x288
Found resolution: 640x360
Found resolution: 960x540
Found resolution: 1280x720
0. 896x504 - URL: 1800_complete.m3u8
1. 320x180 - URL: 192_complete.m3u8
2. 384x216 - URL: 450_complete.m3u8
3. 512x288 - URL: 800_complete.m3u8
4. 640x360 - URL: 1200_complete.m3u8
5. 960x540 - URL: 2500_complete.m3u8
6. 1280x720 - URL: 3500_complete.m3u8
Choose the stream you want: 1
[==================================================] 100.00% (549/549)Video downloaded
Traceback (most recent call last):
  File "eurosportplayer-dl.py", line 874, in <module>
    args_dbg = copy.deepcopy(vars(args))
NameError: name 'exit' is not defined
[10068] Failed to execute script eurosportplayer-dl

**Comment by raffam** [comment]
That doesn't look like a log file generated by the latest version of the script ... in the latest version I have added additional information to the log file on purpose. Are you sure you are using the latest commit? did you run `git pull` before running the script? Can you try to run
```
git reset --hard
git pull
```

and try again? Be careful that you will lose all your changes with this command if you made any

**Comment by raffam** [comment]
Are you running the script directly from the source repository or the Windows executable file instead?

**Comment by thomas012345** [comment]
What i did...?

 

I renamed the "old eurosportplayer-dl" copied your new eurosportplayer-dl in the Dir...

 

yes, tried it with your  "Win.exe" (Windows version)

 

 

I´m not really into python.... :(

 

Gesendet: Montag, 22. April 2019 um 08:58 Uhr
Von: "Raffaele Mancuso" <notifications@github.com>
An: raffam/eurosportplayer-dl <eurosportplayer-dl@noreply.github.com>
Cc: thomas012345 <sidux123@web.de>, Author <author@noreply.github.com>
Betreff: Re: [raffam/eurosportplayer-dl] no plan (#4)


Are you running the script directly from the source repository or the Windows executable file instead?

**Comment by thomas012345** [comment]
tell me... what to do, exactly.....

 

sorry

 

Gesendet: Montag, 22. April 2019 um 08:52 Uhr
Von: "Raffaele Mancuso" <notifications@github.com>
An: raffam/eurosportplayer-dl <eurosportplayer-dl@noreply.github.com>
Cc: thomas012345 <sidux123@web.de>, Author <author@noreply.github.com>
Betreff: Re: [raffam/eurosportplayer-dl] no plan (#4)


That doesn't look like a log file generated by the latest version of the script ... in the latest version I have added additional information to the log file on purpose. Are you sure you are using the latest commit? did you run git pull before running the script? Can you try to run

git reset --hard
git pull


and try again? Be careful that you will lose all your changes with this command if you made any

**Comment by raffam** [comment]
I don't have access to a Windows machine to compile actually. I think installing Python and running the commit is not too hard tough. The README (also available int he GitHub frontpage) explained be all the passages

**Comment by raffam** [comment]
ok, you can try with the new Windows release

**Comment by raffam** [comment]
I am closing for lack of response

**Comment by thomas012345** [comment]
i will try :)

**Comment by thomas012345** [comment]
Windows Release should work "out of the box" ?  or?


p\Es-Down\eurosportplayer-dl.exe --url https://de.eurosportplayer.com/event/radsport-tour-of-yorkshire/b6ece978-9c91-4a30-835a-4315cfc0a6da --user 1473t@gmx.de --password 1Scratched --overwrite --debug
Traceback (most recent call last):
  File "eurosportplayer-dl.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\winprograms\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Crypto\Cipher\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\winprograms\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Crypto\Cipher\_mode_ecb.py", line 47, in <module>
  File "Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win32.pyd': Failed to load dynlib/dll 'C:\\Users\\goldstar\\AppData\\Local\\Temp\\_MEI91722\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp37-win32.pyd'. Most probably this dynlib/dll was not found when the application was frozen., Trying '_raw_ecb.pyd': Failed to load dynlib/dll 'C:\\Users\\goldstar\\AppData\\Local\\Temp\\_MEI91722\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[3948] Failed to execute script eurosportplayer-dl

**Comment by thomas012345** [comment]
why d:\  ?

**Comment by raffam** [comment]
The Windows release is broken as to #5 and https://github.com/pyinstaller/pyinstaller/issues/4212 .... Unfortunately you have to run the source code version for the foreseeable future

**Comment by fatlazycat** [comment]
You could try running it via the Windows Linux Subsystem https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by raffam** [comment]
I wasn't aware of this feature...but just installing Python is more than enough
