### ISSUE TITLE
Video downloading partialy

### ISSUE THREAD

**Issue by Veridiax** [raffam/eurosportplayer-dl#6]
Hi,
I just tried using your script (using source code on Windows). I followed each step in the README and downloaded the video but it was shorter than it is on the website. The video I downloaded had 1h 45min and the video from website is 2h 30min. Every step of the script went without errors, I did not modify any other parameters than the mandatory ones (I provided only url, username and password).

And I know it is not the proper place to write it, but I love your work! As a begginer in Python I learned few things reading your code :)

**Comment by raffam** [comment]
Thanks! Can you provide me a link?

**Comment by raffam** [comment]
Hi @Veridiax , can you provide me a link of the video which suffers this problem

**Comment by raffam** [comment]
Feel free to reopen the issue with an URL I can test in order to reproduce the problem
