### ISSUE TITLE
Localization/dubbing issues

### ISSUE THREAD

**Issue by neunewcomer** [raffam/eurosportplayer-dl#8]
Your downloader works absolutely well for me, however it seems I can only download English dubbing (probably the original). but is it possible to somehow download localized voiceovers?

**Comment by raffam** [comment]
Hello,
Thanks for your feedback. Honestly I never tried. Do you have a link with a localize voiceover I can try?

**Comment by raffam** [comment]
Feel free to reopen it with a link I can try
