### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8a in position 307: character maps to <undefined>

### ISSUE THREAD

**Issue by hagicohen** [raffam/eurosportplayer-dl#9]
Tank you for your customization.
I run your application and get error below. attached log file.
Pleae help me slove this issue.
[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3459722/eurosport-dl.log)

FFMPEG is not present in path. You would not be allowed to join the downloaded video chunks. Do you wish to continue? (Y/N)Y
********** STEP 1 **********
********** STEP 2 **********
********** STEP 3 **********
********** STEP 4 **********
********** STEP 5 **********
********** STEP 6 **********
********** STEP 7 **********
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 897, in <module>
    main(args)
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 725, in main
    master_file = fileh.readlines()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8a in position 307: character maps to <undefined>

**Comment by raffam** [comment]
Hello, thanks for your report. Please, I would need the full command line you are running (with username and password covered by asterisks, of course) and also having the log file would be useful. You can obtain a log file by running the script with the `--debug` command line, it should generate a `.log` file you could attach here.
Thanks

**Comment by raffam** [comment]
Hello,
thanks for your detailed bug report. Could you please update your python to a version >= 3.3, update eurosportplayer to the lastest commit, and try running it again?
Best,
Raffaele

**Comment by hagicohen** [comment]
HI,
Thank you back (I dont find you mail) 
I run python 3.7. I dont know what you mean last version eurosportplayer (it running on PC)

my cmd:
C:\Users\USER\Desktop\eurosportplayer-dl-master>C:\Users\USER\AppData\Local\Programs\Python\Python37-32\python.exe C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py --url https://il.eurosportplayer.com/event/tour-de-france-best-of/6cc8c849-0c3b-410d-a6fa-36dd03dedb74 --user xxxxx --password xxxxx

If you need more detailes please feel free to ask 


[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3461064/eurosport-dl.log)

**Comment by raffam** [comment]
Hello,
by last version eurosportplayer I mean the latest commit. 
You should `cd` in `C:\Users\USER\Desktop\eurosportplayer-dl-master` and run 
`git pull`

or re-download the source code if you used this method

**Comment by hagicohen** [comment]
download new issue,
********** STEP 10 **********
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 973/973 [21:16<00:00,  1.32it/s]
[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 875, in <module>
    raise(e)
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 871, in <module>
    main(args)
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 805, in main
    concat_video_frames(list_file, "./download/final.mp4")
  File "C:\Users\USER\Desktop\eurosportplayer-dl-master\eurosportplayer-dl.py", line 524, in concat_video_frames
    subprocess.call(tocall)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
[eurosport-dl.log](https://github.com/raffam/eurosportplayer-dl/files/3465156/eurosport-dl.log)

**Comment by raffam** [comment]
This is because you don't have FFMPEG in your path. You need to install it

**Comment by raffam** [comment]
I added an option to re-check for FFMPEG at the end of the download. Please open another issue should you experience other problems
